### ISSUE TITLE
align-self is missing

### ISSUE THREAD

**Issue by jochienabuurs** [nicoqh/inuit-flexgrid#1]
Nice extension of inuit!

Is there a reason why align-self isn't included?

**Comment by nicoqh** [comment]
That seems like a nice addition :)

Since we already have these modifiers on `o-grid`:

* `o-grid--middle`: Vertically center cells. Uses `align-items: center`.
* `o-grid--bottom`: Align cells to the bottom. Uses `align-items: flex-end`.

how about doing:

* `o-grid__cell--middle`: Vertically center the cell. Uses `align-self: center`.
* `o-grid__cell--top`: Align the cell to the top. Uses `align-self: flex-start`.
* `o-grid__cell--bottom`: Align the cell to the bottom. Uses `align-self: flex-end`.

(We haven't included every possible `align-items` and `align-self` value, and could consider adding more.)

Feel free to make a PR, or I'll do it myself.

**Comment by jochienabuurs** [comment]
Yeah, makes sense to use ```o-grid__cell--middle``` and such.
I'll try to find some time today or tomorrow to make a pr

**Comment by nicoqh** [comment]
Done in #2
